"use client";
import Link from "next/link";
import { UsersRound, CircleCheck, FileText, ArrowRight } from "lucide-react";
import { useAdmin } from "./admin-provider";
import { useLanguage } from "../../_components/language-provider";
export function Dashboard() {
 const { professionals } = useAdmin(); const { language } = useLanguage(); const km = language === "km";
 const stats = [{ title: km ? "អ្នកជំនាញសរុប" : "Total professionals", value: professionals.length, icon: UsersRound }, { title: km ? "បានផ្សព្វផ្សាយ" : "Published profiles", value: professionals.filter(p => p.status === "published").length, icon: CircleCheck }, { title: km ? "សេចក្តីព្រាង" : "Draft profiles", value: professionals.filter(p => p.status === "draft").length, icon: FileText }];
 return <><p className="text-sm font-medium text-arom">{km ? "កន្លែងគ្រប់គ្រង ARom" : "ARom workspace"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{km ? "ទិដ្ឋភាពទូទៅ" : "A little care goes a long way"}</h1><p className="mt-3 text-sm text-ink-muted">{km ? "គ្រប់គ្រងអ្នកជំនាញ និងរៀបចំមាតិកាសម្រាប់សហគមន៍។" : "Manage the people and content that support our community."}</p>
 <div className="mt-8 grid gap-4 sm:grid-cols-3">{stats.map(({ title, value, icon: Icon }) => <section key={title} className="rounded-3xl border border-arom-border bg-white p-6 shadow-sm"><Icon className="rounded-xl bg-arom-soft p-2 text-arom" size={40}/><p className="mt-5 text-3xl font-semibold">{value}</p><h2 className="mt-2 text-sm text-ink-muted">{title}</h2></section>)}</div>
 <section className="mt-7 rounded-3xl border border-arom-border bg-white p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">{km ? "បញ្ជីអ្នកជំនាញ" : "Professional directory"}</h2><p className="mt-2 text-sm text-ink-muted">{km ? "បន្ថែម និងកែសម្រួលប្រវត្តិរូបអ្នកជំនាញ។" : "Keep professional profiles clear and up to date."}</p></div><Link href="/admin/professionals" className="flex items-center gap-2 rounded-full bg-arom px-5 py-3 text-sm text-white">{km ? "គ្រប់គ្រងអ្នកជំនាញ" : "Manage professionals"}<ArrowRight size={16}/></Link></div><div className="mt-6 divide-y divide-arom-border">{professionals.slice(-4).reverse().map(p => <div key={p.id} className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-medium">{km && p.kmName ? p.kmName : p.name}</p><p className="mt-1 text-xs text-ink-muted">{km && p.kmRole ? p.kmRole : p.role}</p></div><span className="rounded-full bg-arom-wash px-3 py-1 text-xs text-arom">{p.status === "published" ? (km ? "បានផ្សព្វផ្សាយ" : "Published") : p.status === "draft" ? (km ? "សេចក្តីព្រាង" : "Draft") : (km ? "បានទុកក្នុងបណ្ណសារ" : "Archived")}</span></div>)}</div></section>
 <p className="mt-6 text-sm text-ink-muted">{km ? "បន្ទាប់៖ អ្នកប្រើប្រាស់ មាតិកា ការកក់ និងសហគមន៍។" : "Next modules: users, MindGuide content, bookings, and community."}</p></>;
}
