"use client";
import Image from "next/image";
import { useState } from "react";
import { Plus, Search, Pencil, Archive, UsersRound, RotateCcw } from "lucide-react";
import { useAdmin } from "./admin-provider";
import { ProfessionalForm } from "./professional-form";
import type { Professional, PublicationStatus } from "../_data/professionals";
import { useLanguage } from "../../_components/language-provider";
export function ProfessionalsView() {
 const { professionals, save } = useAdmin(); const { language } = useLanguage(); const km = language === "km";
 const [query, setQuery] = useState(""); const [status, setStatus] = useState<PublicationStatus | "all">("all");
 const [editor, setEditor] = useState<{ record: Professional | null } | null>(null);
 const [notice, setNotice] = useState("");
 const labels = { published: km ? "បានផ្សព្វផ្សាយ" : "Published", draft: km ? "សេចក្តីព្រាង" : "Draft", archived: km ? "បានទុកក្នុងបណ្ណសារ" : "Archived" };
 const visible = professionals.filter(p => (status === "all" || p.status === status) && `${p.name} ${p.kmName} ${p.role} ${p.specialties.join(" ")}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 return <><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-medium text-arom">{km ? "ការថែទាំប្រកបដោយទំនុកចិត្ត" : "People who make a difference"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{km ? "អ្នកជំនាញ" : "Professionals"}</h1><p className="mt-3 text-sm text-ink-muted">{km ? "គ្រប់គ្រងប្រវត្តិរូប ជំនាញ និងការផ្សព្វផ្សាយ។" : "Manage profiles, specialties, and publication status."}</p></div><button onClick={() => setEditor({record:null})} className="flex items-center gap-2 rounded-full bg-arom px-5 py-3 text-sm font-medium text-white hover:bg-arom-deep"><Plus size={18}/>{km ? "បន្ថែមអ្នកជំនាញ" : "Add professional"}</button></div>
 <div className="mt-8 grid gap-4 sm:grid-cols-3">{(["published","draft","archived"] as const).map(s => <button key={s} onClick={() => setStatus(status === s ? "all" : s)} aria-pressed={status === s} className={`rounded-2xl border bg-white p-5 text-left ${status === s ? "border-arom ring-2 ring-arom/10" : "border-arom-border"}`}><p className="text-2xl font-semibold">{professionals.filter(p=>p.status===s).length}</p><p className="mt-1 text-sm text-ink-muted">{labels[s]}</p></button>)}</div>
 <section className="mt-6 overflow-hidden rounded-3xl border border-arom-border bg-white shadow-sm"><div className="flex flex-wrap items-center gap-3 border-b border-arom-border p-5"><div className="relative min-w-48 flex-1"><Search size={18} className="absolute left-3 top-3 text-ink-muted"/><input aria-label={km ? "ស្វែងរកអ្នកជំនាញ" : "Search professionals"} placeholder={km ? "ស្វែងរកឈ្មោះ ឬជំនាញ..." : "Search by name, title, or specialty..."} value={query} onChange={e => setQuery(e.target.value)} className="w-full rounded-xl border border-arom-border bg-arom-wash py-2.5 pl-10 pr-3 text-sm outline-none focus:border-arom focus:ring-2 focus:ring-arom/15"/></div><select aria-label={km ? "តម្រងស្ថានភាព" : "Filter by status"} value={status} onChange={e=>setStatus(e.target.value as PublicationStatus | "all")} className="rounded-xl border border-arom-border bg-white px-3 py-2.5 text-sm"><option value="all">{km ? "គ្រប់ស្ថានភាព" : "All statuses"}</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[740px] text-left text-sm"><caption className="sr-only">{km ? "បញ្ជីអ្នកជំនាញ" : "Professional profiles"}</caption><thead className="bg-arom-wash text-xs text-ink-muted"><tr>{(km ? ["អ្នកជំនាញ","ជំនាញ","ជំនួប","ស្ថានភាព","សកម្មភាព"] : ["Professional","Specialties","Session","Status","Actions"]).map(h=><th key={h} scope="col" className="px-5 py-4 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-arom-border">{visible.map(p=><tr key={p.id} className="hover:bg-arom-wash/50"><td className="px-5 py-5"><div className="flex items-center gap-3">{p.image ? <Image src={p.image} width={44} height={44} alt="" className="h-11 w-11 rounded-full object-cover"/> : <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-arom-soft text-arom"><UsersRound size={20}/></span>}<div><p className="font-medium">{km && p.kmName ? p.kmName : p.name}</p><p className="mt-1 text-xs text-ink-muted">{km && p.kmRole ? p.kmRole : p.role}</p></div></div></td><td className="max-w-56 px-5 py-5"><div className="flex flex-wrap gap-1.5">{p.specialties.map(s=><span key={s} className="rounded-lg bg-arom-wash px-2 py-1 text-xs text-arom">{s}</span>)}</div></td><td className="px-5 py-5 text-ink-muted">{p.session === "Both" ? (km ? "ទាំងពីរ" : "Both") : p.session === "Online" ? (km ? "អនឡាញ" : "Online") : (km ? "ជួបផ្ទាល់" : "In person")}</td><td className="px-5 py-5"><span className={`whitespace-nowrap rounded-full px-3 py-1 text-xs ${p.status === "published" ? "bg-arom-soft text-arom" : p.status === "draft" ? "bg-amber-50 text-amber-800" : "bg-gray-100 text-gray-600"}`}>{labels[p.status]}</span></td><td className="px-5 py-5"><div className="flex gap-2"><button aria-label={`${km ? "កែសម្រួល" : "Edit"} ${p.name}`} onClick={()=>setEditor({record:p})} className="rounded-lg border border-arom-border p-2 text-arom hover:bg-arom-soft"><Pencil size={16}/></button><button aria-label={`${p.status === "archived" ? "Restore as draft" : "Archive"} ${p.name}`} onClick={()=>{save({...p,status:p.status === "archived" ? "draft" : "archived"});setNotice(km ? "បានធ្វើបច្ចុប្បន្នភាពស្ថានភាព។" : `${p.name}: ${p.status === "archived" ? "restored as draft" : "archived"}.`);}} className="rounded-lg border border-arom-border p-2 text-ink-muted hover:bg-arom-soft">{p.status === "archived" ? <RotateCcw size={16}/> : <Archive size={16}/>}</button></div></td></tr>)}</tbody></table></div>
 {!visible.length && <div className="p-12 text-center"><UsersRound size={32} className="mx-auto text-ink-muted"/><h2 className="mt-4 font-medium">{km ? "មិនមានលទ្ធផល" : "No matching professionals"}</h2><p className="mt-2 text-sm text-ink-muted">{km ? "សាកល្បងពាក្យស្វែងរក ឬតម្រងផ្សេង។" : "Try another search or clear your filters."}</p><button onClick={()=>{setQuery("");setStatus("all");}} className="mt-4 text-sm font-medium text-arom underline">{km ? "សម្អាតតម្រង" : "Clear filters"}</button></div>}
 <p className="border-t border-arom-border px-5 py-4 text-xs text-ink-muted">{km ? "លទ្ធផល" : "Showing"} {visible.length} / {professionals.length}</p></section><p role="status" aria-live="polite" className="mt-4 min-h-5 text-sm text-arom">{notice}</p>
 {editor && <ProfessionalForm record={editor.record} onClose={()=>setEditor(null)} onSave={record=>{save(record);setEditor(null);setNotice(km ? "បានរក្សាទុកប្រវត្តិរូប។" : `${record.name}: profile saved.`);}}/>}</>;
}
